"""them type vao db

Revision ID: 746885aecd51
Revises: 8a7498678dfc
Create Date: 2025-05-11 22:42:12.466856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746885aecd51'
down_revision = '8a7498678dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
